### ISSUE TITLE
Error: Cannot find module 'gulp-connect'

### ISSUE THREAD

**Issue by FurianXO** [ArqTras/nodejs-pool#4]
deploy_electroneum.bash: 14: deploy_electroneum.bash: Syntax error: redirection unexpected

This is a fresh install of ubuntu 16.04

**Comment by FurianXO** [comment]
This failed using these instructions - https://github.com/ArqTras/nodejs-pool/wiki
Seems to be working using these - https://github.com/ArqTras/nodejs-pool

stay tuned.

**Comment by FurianXO** [comment]
```
Error: Cannot find module 'gulp-connect'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/superuser/poolui/gulpfile.js:2:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm WARN xmrpoolui@ No repository field.
npm WARN xmrpoolui@ license should be a valid SPDX license expression
npm ERR! Linux 4.4.0-104-generic
npm ERR! argv "/home/superuser/.nvm/versions/node/v6.9.2/bin/node" "/home/superuser/.nvm/versions/node/v6.9.2/bin/npm" "install"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! xmrpoolui@ postinstall: `bower install && gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xmrpoolui@ postinstall script 'bower install && gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the xmrpoolui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install && gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs xmrpoolui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls xmrpoolui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/superuser/poolui/npm-debug.log
```


and then later....

```

[Install]
WantedBy=multi-user.target

Target path
/etc/systemd/system/pm2-superuser.service
Command list
[ 'systemctl enable pm2-superuser',
  'systemctl start pm2-superuser',
  'systemctl daemon-reload',
  'systemctl status pm2-superuser' ]
[PM2] Writing init configuration in /etc/systemd/system/pm2-superuser.service
[PM2] Making script booting at startup...
>>> Executing systemctl enable pm2-superuser
Created symlink from /etc/systemd/system/multi-user.target.wants/pm2-superuser.service to /etc/systemd/system/pm2-superuser.service.
[DONE]
>>> Executing systemctl start pm2-superuser
Job for pm2-superuser.service failed because the control process exited with error code. See "systemctl status pm2-superuser.service" and "journalctl -xe" for details.
[ERROR] Exit code : 1
[PM2][ERROR] systemctl start pm2-superuser failed, see error above.
Installing pm2-logrotate in the background!
mysql: [Warning] Using a password on the command line interface can be insecure.
[PM2] Spawning PM2 daemon with pm2_home=/home/superuser/.pm2
[PM2] PM2 Successfully daemonized
[PM2][Module] Installing module pm2-logrotate
[PM2][Module] Calling [NPM] to install pm2-logrotate ...

```

**Comment by bobbieltd** [comment]
Sorry. He’ll fix the path in the bash. I aleardy PR him.

**Comment by FurianXO** [comment]
What's interesting is I get Error: Cannot find module 'gulp-connect' on the original monero build now as well.  This worked fine a couple of days ago.  I wonder if something in the package library changed for ubuntu 16.04?

**Comment by ArqTras** [comment]
Use as sudouser pooldaemon

**Comment by FurianXO** [comment]
pooldaemon@etnpool:~$ grep -Po '^sudo.+:\K.*$' /etc/group
pooldaemon

#includedir /etc/sudoers.d
pooldaemon ALL=(ALL) NOPASSWD:ALL

Still get Error: Cannot find module 'gulp-connect'

**Comment by ArqTras** [comment]
I make installation yesterday without issue 
Join discord https://discordapp.com/invite/vGeRWQF
And Prv

**Comment by ArqTras** [comment]
Working - need to put pooldaemon under root user in /etc/sudoers

**Comment by FurianXO** [comment]
clarifying the solution ArqTras found... this confused me.

This:

```
#
# This file MUST be edited with the 'visudo' command as root.
#
# Please consider adding local content in /etc/sudoers.d/ instead of
# directly modifying this file.
#
# See the man page for details on how to write a sudoers file.
#
Defaults        env_reset
Defaults        mail_badpass
Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"

# Host alias specification

# User alias specification

# Cmnd alias specification

# User privilege specification
root    ALL=(ALL:ALL) ALL
pooldaemon ALL=(ALL) NOPASSWD:ALL

# Members of the admin group may gain root privileges
%admin ALL=(ALL) ALL

# Allow members of group sudo to execute any command
%sudo   ALL=(ALL:ALL) ALL

# See sudoers(5) for more information on "#include" directives:

#includedir /etc/sudoers.d

```

Not this:

```
#
# This file MUST be edited with the 'visudo' command as root.
#
# Please consider adding local content in /etc/sudoers.d/ instead of
# directly modifying this file.
#
# See the man page for details on how to write a sudoers file.
#
Defaults        env_reset
Defaults        mail_badpass
Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"

# Host alias specification

# User alias specification

# Cmnd alias specification

# User privilege specification
root    ALL=(ALL:ALL) ALL

# Members of the admin group may gain root privileges
%admin ALL=(ALL) ALL

# Allow members of group sudo to execute any command
%sudo   ALL=(ALL:ALL) ALL

# See sudoers(5) for more information on "#include" directives:

#includedir /etc/sudoers.d
pooldaemon ALL=(ALL) NOPASSWD:ALL
```

**Comment by bobbieltd** [comment]
@FurianXO It’s written in readme. It needs sudo command to install some packages.
