### ISSUE TITLE
Payment don't go to miners

### ISSUE THREAD

**Issue by ArqTras** [ArqTras/nodejs-pool#5]
Api error 

TypeError: Cannot read property 'owed' of undefined
    at /home/pooldaemon/nodejs-pool/lib/api.js:592:44
    at Array.forEach (native)
    at /home/pooldaemon/nodejs-pool/lib/api.js:591:22
    at tryCatcher (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
2018-01-03 16:30 +00:00: Unhandled rejection TypeError: Cannot read property 'owed' of undefined
    at /home/pooldaemon/nodejs-pool/lib/api.js:592:44
    at Array.forEach (native)
    at /home/pooldaemon/nodejs-pool/lib/api.js:591:22
    at tryCatcher (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
2018-01-03 16:32 +00:00: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TypeError: Cannot read property 'owed' of undefined

Check for solution without success: https://github.com/Snipa22/nodejs-pool/issues/180
Any informations sugesstions ?

**Comment by bobbieltd** [comment]
Perhaps, some ideas with this ?
https://github.com/Snipa22/nodejs-pool/issues/61

**Comment by ArqTras** [comment]
Payments solved please update your code

**Comment by bobbieltd** [comment]
I can confirm that ArqTras’ repo works. Problem solved. I’d love if ArqTras open his own ETN pool so we can change our experiences. Lacks of active ETN pool owners at the moment.
