### ISSUE TITLE
poolBootMsg error

### ISSUE THREAD

**Issue by tenpin784** [ArqTras/nodejs-pool#5]
Trying to set up alloy using your scripts (good work by the way). 

I am getting the following error:

2018-03-24 14:49 +00:00: ReferenceError: poolBotMsg is not defined
    at module.exports (/home/jbarbieri/nodejs-pool/lib/support.js:202:21)
    at Object.<anonymous> (/home/jbarbieri/nodejs-pool/init.js:10:45)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Object.<anonymous> (/home/jbarbieri/.nvm/versions/node/v8.9.3/lib/node_modules/pm2/lib/ProcessContainerFork.js:83:21)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

Any thoughts?

jbarbieri@xao:~/.pm2/logs$ node -v
v8.9.3
jbarbieri@xao:~/.pm2/logs$ npm -v
5.5.1

   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.5.1 → 5.8.0    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯

jbarbieri@xao:~/.pm2/logs$

**Comment by tenpin784** [comment]
I actually get the same error on both softwares.
